### ISSUE TITLE
Contents of removed begin..end gets wrong line number

### ISSUE THREAD

**Issue by mvz** [seattlerb/ruby_parser#290]
```ruby
[7] pry(main)> ENV['VERBOSE'] = 'true'
=> "true"
[8] pry(main)> RubyParser.for_current_ruby.parse("begin\nfoo\nend\n")
=> s(:call, nil, :foo).line(1)
```

The call to `foo` is on line 2, but gets parsed as line 1.

**Comment by zenspider** [comment]
OK... philosophical question:

```ruby
begin
  a
rescue
  b
rescue
  c
end
```

becomes:

```ruby
s(:begin,
  s(:rescue,
    s(:call, nil, :a).line(2),
    s(:resbody, s(:array),
      s(:call, nil, :b)),
    s(:resbody, s(:array),
      s(:call, nil, :c))
   ).line(2)
 ).line(1)
```

(several line numbers omitted for readability)

When `remove_begin` gets called, it normally sets the inner thing (`:rescue` on line "2") to the line of the begin it is removing (line 1)... If I fix your bug above, I change the behavior below so that the rescue is now line 2 and not line 1.

Does this FEEL right? (yes, I realize that the rescue token is on line 3... that's a separate matter)

**Comment by zenspider** [comment]
I think yes, but I'm totally open to debating this...

In which case, this is fixed.

**Comment by mvz** [comment]
> Does this FEEL right?

Yes, I think so.
